class Post{
  late int _menu;
  late String _col;
  late String _dodo;
  late List<Map<String, dynamic>> jfk;


  Post.fromJson(this.jfk){
    jfk = this.jfk ;
  }

  Post(this._menu, this._col, this._dodo);

  @override
  String toString() {
    return '{_menu:$_menu,  _col:$_col, _dodo:$_dodo}';
  }


  List<Map<String, dynamic>> getList(){
    return jfk;
  }

  // Post.fromJson(Map<String, dynamic> jjj) {
  //   _menu = jjj["_menu"];
  //   _col = jjj["_col"];
  //   _dodo = jjj["_dodo"];
  // }

  Map<String, dynamic>? toJson() {
    final map = <String, dynamic>{};
    map['_menu'] = _menu;
    map['_col'] = _col;
    map['_dodo'] = _dodo;
  }
}
//
// class Autogenerated {
//   int userId;
//   int id;
//   String title;
//   bool completed;
//
//   Autogenerated({this.userId, this.id, this.title, this.completed});
//
//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     userId = json['userId'];
//     id = json['id'];
//     title = json['title'];
//     completed = json['completed'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['userId'] = this.userId;
//     data['id'] = this.id;
//     data['title'] = this.title;
//     data['completed'] = this.completed;
//     return data;
//   }
// }

// jfk = [{ "_menu": '15,000원', "_col": '공기밥 무료', "_dodo": 0xffFFE959 }, { "_menu": '7,000원', "_col": '공기밥 천원', "_dodo": 0xffB2FF59 }, { "_menu": '3,500원', "_col": '김치 셀프', "_dodo": 0xffAD6BB3 }];
